In [10]:
import numpy as np
import pandas as pd
import torch
import pickle
import matplotlib.pyplot as plt
from lpne.models import DcsfaNmf
from scipy.stats import wilcoxon

MODEL_FILE = "/hpc/home/mk423/Anxiety/FullDataWork/Models/Final_mt_Model_500_epochs.pt"
DATA_FILE = "/work/mk423/Social_v_1_2/SocialData_v_1_2.pkl"

keep_mice_1 = "/work/mk423/Social_v_1_2/SocialMice_Format1.xlsx"
keep_mice_2 = "/work/mk423/Social_v_1_2/SocialMice_Format2.xlsx"
PROJECT_PATH = "/hpc/home/mk423/Anxiety/FullDataWork/Projections/"

analysis_mice = ["Mouse0630","Mouse0631","Mouse0632","Mouse0633","Mouse0634","Mouse0640","Mouse0641","Mouse0642","Mouse0643","Mouse0644","Mouse5321","Mouse5331"]

In [17]:
df = pd.read_csv(PROJECT_PATH + "Anx_Nets_Social_vs_Object_means.csv")
df = df[df["mouse"].isin(analysis_mice)]
df

,mouse,social mean agg,social mean net 1,social mean net 2,social mean net 3,object mean agg,object mean net 1,object mean net 2,object mean net 3
0,Mouse0630,4.189760,0.120192,0.179339,0.030794,4.321705,0.122935,0.185761,0.028046
1,Mouse0631,3.449790,0.098050,0.147030,0.052390,3.514428,0.097990,0.151137,0.047892
2,Mouse0632,4.366596,0.106258,0.197735,0.039906,4.410421,0.109559,0.198582,0.036270
3,Mouse0633,3.868243,0.113798,0.163822,0.030577,3.928467,0.115123,0.166750,0.028410
4,Mouse0634,4.678820,0.122561,0.207272,0.030961,4.672527,0.121370,0.207661,0.029415
5,Mouse0640,2.856407,0.066479,0.129781,0.057161,2.796587,0.065865,0.126764,0.052319
6,Mouse0641,2.475447,0.101225,0.087741,0.029067,2.438094,0.101600,0.085361,0.027198
7,Mouse0642,4.770456,0.121154,0.212894,0.047112,4.885114,0.125274,0.217518,0.043245
8,Mouse0643,4.194436,0.100705,0.190607,0.041416,4.174632,0.103893,0.187647,0.039094
9,Mouse0644,4.475792,0.088263,0.214863,0.039713,4.607262,0.091640,0.221030,0.033589
10,Mouse5321,4.251720,0.111923,0.187509,0.040106,4.161174,0.117474,0.178936,0.037392
11,Mouse5331,3.167399,0.096579,0.131356,0.043213,3.124829,0.092637,0.130931,0.047538

In [18]:
#network 1
results = wilcoxon(df["object mean net 1"],df["social mean net 1"],alternative="less")
print(results)

WilcoxonResult(statistic=60.0, pvalue=0.953857421875)

In [19]:
#network 2
results = wilcoxon(df["object mean net 2"],df["social mean net 2"],alternative="less")
print(results)

WilcoxonResult(statistic=47.0, pvalue=0.74072265625)